server {
    listen 80;
    server_name localhost;

    location /player/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /player/index.html;
    }

    location /player/assets/ {
        alias /usr/share/nginx/html/assets/;
        access_log off;
    }

    location ~ ^/player/(.+\.(js|css|ico|svg|map))$ {
        alias /usr/share/nginx/html/$1;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location = / {
        return 301 /player/;
    }
}